TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := ipcbench.camkes

Ping_CFILES := src/ping.c
Ping_HFILES := include/ipcbench.h
Pong_CFILES := src/pong.c
Pong_HFILES := include/ipcbench.h
Guzzle_CFILES := src/guzzle.c

include ${PWD}/tools/camkes/camkes.mk
